Attribute VB_Name = "Language"
Option Explicit

' ================ English ================
' FormSplash
Public Const TXTMessage1 As String = "Please select model:"
Public Const TXTVersion As String = "Version"

' FormMain
Public Const TXTTitle As String = "Auto White Balance Modulation"
Public Const TXTBarcodeError As String = "Please check the barcode of TV. Its length is: "
Public Const TXTBarcodeErrorTitle As String = "Barcode Error"
Public Const TXTCaDisconnectHint As String = "CA310/CA210 disconnected. Please click 'Function'->'Connect CA310/CA210' to connect it!"
Public Const TXTGainCool1Wrong As String = "ColorTemp_COOL_1 is Wrong, Please Check Again."
Public Const TXTGainCool2Wrong As String = "ColorTemp_COOL_2 is Wrong, Please Check Again."
Public Const TXTGainNormalWrong As String = "ColorTemp_NORMAL is Wrong, Please Check Again."
Public Const TXTGainWarm1Wrong As String = "ColorTemp_WARM_1 is Wrong, Please Check Again."
Public Const TXTGainWarm2Wrong As String = "ColorTemp_WARM_2 is Wrong, Please Check Again."
Public Const TXTOffsetCool1Wrong As String = "OFFSET_Color_COOL_1 is Wrong, Please Check Again."
Public Const TXTOffsetCool2Wrong As String = "OFFSET_Color_COOL_2 is Wrong, Please Check Again."
Public Const TXTOffsetNormalWrong As String = "OFFSET_Color_NORMAL is Wrong, Please Check Again."
Public Const TXTOffsetWarm1Wrong As String = "OFFSET_Color_WARM_1 is Wrong, Please Check Again."
Public Const TXTOffsetWarm2Wrong As String = "OFFSET_Color_WARM_2 is Wrong, Please Check Again."
Public Const TXTLvTooLow As String = "Luminance is too low."
Public Const TXTChk As String = "CHECK"
Public Const TXTDVIWrong As String = "Can not Write DVI EDID."
Public Const TXTCalFail As String = "Calibrate FAIL.(AUTO LEVEL)"
Public Const TXTRS232Er As String = "RS232 Connector Error"
Public Const TXTDSUBFail As String = "Read DSUB EDID FAIL"
Public Const TXTHDMI2ChkWrong As String = "HDMI2 CheckSum is Wrong"
Public Const TXTHDMI2EDIDWrong As String = "Can not Write HDMI-2 EDID."
Public Const TXTMinBriTooHigh As String = "min_Brightness is over SPEC."
Public Const TXTFWVerWrong As String = "FW Version is Wrong."
Public Const TXTOSDSNWriteWrong As String = "Can not Write OSD-SN."
Public Const TXTMaxBriTooHigh As String = "max_Brightness is over SPEC."
Public Const TXTCT5000Wrong As String = "ColorTemp_5000 is Wrong, Please Check Again."
Public Const TXTCT3000Wrong As String = "ColorTemp_3000 is Wrong, Please Check Again."
Public Const TXTLSDataWrong As String = "LightSensor Data is Wrong, Please Check Again."
Public Const TXTSNLenWrong As String = "条形码长度不对，请确认！"
Public Const TXTChkCA210 As String = "Please check the CA210 Probe is OK or not."
Public Const TXTRun As String = "RUN..."
Public Const TXTWhite As String = "WHITE"
Public Const TXTGrey As String = "GREY"
Public Const TXTPass As String = "PASS"
Public Const TXTFail As String = "FAIL"
Public Const TXTErrCode As String = "Error code:"
'Menu
Public Const TXTFun As String = "Function"
Public Const TXTConnectCA As String = "Connect CA310/CA210"
Public Const TXTDisConnectCA As String = "DisConnect CA310/CA210(&D)"
Public Const TXTSet As String = "Setting"
Public Const TXTSetSpec As String = "Set Spec"
Public Const TXTDiscription As String = "Description"
Public Const TXTAbout As String = "About"
'Interface
Public Const TXTCOOL1 As String = "COOL1"
Public Const TXTCOOL2 As String = "COOL2"
Public Const TXTSTD As String = "STANDARD"
Public Const TXTWARM1 As String = "WARM1"
Public Const TXTWARM2 As String = "WARM2"
Public Const TXTINITIAL As String = "INITIAL"
Public Const TXTSPEC As String = "SPEC"
Public Const TXTChkResult As String = "ADJUST COLOR"


' ================ English ================
